version: '3'
services:
  
  #PHP Service 1
  php1:
    build: ./
    container_name: php1
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php1
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - docker-final-network
    depends_on:
      - db
    entrypoint: ["bash", "laravel_start_launch.sh"]

  #PHP Service 2
  php2:
    build: ./
    container_name: php2
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php2
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - docker-final-network
    depends_on:
      - db
    entrypoint: ["bash", "laravel_start_launch.sh"]

  nginx1:
    image: nginx:latest
    container_name: nginx1
    restart: unless-stopped
    tty: true
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - ./nginx-config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - docker-final-network
    depends_on:
      - php1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx1.rule=PathPrefix(`/nginx1`)"
      - "traefik.http.services.nginx1.loadbalancer.server.port=80"

  nginx2:
    image: nginx:latest
    container_name: nginx2
    restart: unless-stopped
    tty: true
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www
      - ./nginx-config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - docker-final-network
    depends_on:
      - php2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx2.rule=PathPrefix(`/nginx2`)"
      - "traefik.http.services.nginx2.loadbalancer.server.port=80"

  reverse-proxy:
    image: traefik:v2.10
    container_name: traefik
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./config.yml:/path/to/dynamic.yml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker-final-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - docker-final-network

#Docker Networks
networks:
  docker-final-network:

#Volumes
volumes:
  dbdata:
